import { Layout } from "@/components/layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Shield, FileText, RotateCcw, Mail, Lock, ExternalLink } from "lucide-react";

const SECTIONS = [
  {
    id: "privacy",
    icon: Shield,
    title: "Privacy Policy",
    badge: "Last updated: April 2026",
    color: "text-blue-400",
    bg: "bg-blue-400/10",
    content: [
      {
        heading: "What we collect",
        body: "We collect only what's necessary to operate Spark: your generated content (ideas, bundles, scripts) that you choose to save, and anonymous usage stats to improve the product. We do not collect personal information without your consent."
      },
      {
        heading: "How we use your data",
        body: "Your saved ideas and generated content are stored to power your experience in Spark. We never sell your data to third parties. Usage stats are used in aggregate, never linked to individuals."
      },
      {
        heading: "Cookies",
        body: "Spark uses minimal, functional cookies only. No tracking cookies, no advertising networks, no third-party analytics that profile you across the web."
      },
      {
        heading: "Data retention",
        body: "Your data is kept as long as your account is active. You may delete your saved ideas at any time from the Assets page. Account deletion (coming with auth) will remove all your data."
      },
    ]
  },
  {
    id: "terms",
    icon: FileText,
    title: "Terms of Service",
    badge: "Last updated: April 2026",
    color: "text-purple-400",
    bg: "bg-purple-400/10",
    content: [
      {
        heading: "Acceptable use",
        body: "Spark is for lawful commerce and content creation. You may not use Spark to generate content that is deceptive, harmful, or violates applicable laws. You retain full ownership of all content you generate."
      },
      {
        heading: "AI-generated content",
        body: "Content generated by Spark is provided as-is. You are responsible for reviewing, editing, and publishing any AI-generated content. Spark does not guarantee accuracy, completeness, or commercial success."
      },
      {
        heading: "Account and access",
        body: "Free accounts are subject to daily usage limits. Abuse of the platform (e.g. scraping, rate limit circumvention) may result in suspension. Pro plan limits are as described on the Pricing page."
      },
      {
        heading: "Modifications",
        body: "We reserve the right to modify these terms. Continued use of Spark after changes are posted constitutes acceptance. Material changes will be communicated via in-app notice."
      },
    ]
  },
  {
    id: "refund",
    icon: RotateCcw,
    title: "Refund Policy",
    badge: "Fair and simple",
    color: "text-green-400",
    bg: "bg-green-400/10",
    content: [
      {
        heading: "30-day money-back guarantee",
        body: "If you upgrade to Pro and aren't satisfied within the first 30 days, contact us for a full refund. No questions asked."
      },
      {
        heading: "Annual plans",
        body: "Annual plan refunds are available within 30 days of purchase. After 30 days, we'll prorate the remaining months if there are extenuating circumstances."
      },
      {
        heading: "How to request",
        body: "Email support with your account email and reason. We process all refund requests within 3 business days."
      },
    ]
  },
  {
    id: "contact",
    icon: Mail,
    title: "Contact Support",
    badge: "We're here to help",
    color: "text-orange-400",
    bg: "bg-orange-400/10",
    content: [
      {
        heading: "General support",
        body: "For questions about your account, features, or bugs, reach out and we'll get back to you within 24 hours on business days."
      },
      {
        heading: "Billing support",
        body: "For subscription, billing, or refund questions, contact us directly and we'll resolve it quickly."
      },
      {
        heading: "Feature requests",
        body: "Have an idea for Spark? We love hearing from users. Feature requests help shape our roadmap."
      },
    ]
  },
];

export default function Trust() {
  return (
    <Layout>
      <div className="w-full max-w-3xl space-y-8 animate-in fade-in duration-500">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Lock className="h-5 w-5 text-primary" />
            <h1 className="text-3xl font-bold tracking-tight">Trust & Legal</h1>
          </div>
          <p className="text-muted-foreground">Privacy, terms, refunds, and support — all in one place.</p>
        </div>

        <div className="flex flex-wrap gap-3">
          {SECTIONS.map(s => (
            <a key={s.id} href={`#${s.id}`} className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-border/50 text-sm text-muted-foreground hover:text-foreground hover:border-border transition-colors">
              <s.icon className={`h-3.5 w-3.5 ${s.color}`} />
              {s.title}
            </a>
          ))}
        </div>

        <div className="space-y-8">
          {SECTIONS.map(section => (
            <section key={section.id} id={section.id} className="scroll-mt-8 space-y-4">
              <div className="flex items-center gap-3">
                <div className={`h-8 w-8 rounded-lg ${section.bg} flex items-center justify-center`}>
                  <section.icon className={`h-4 w-4 ${section.color}`} />
                </div>
                <div>
                  <h2 className="text-xl font-bold">{section.title}</h2>
                  <p className="text-xs text-muted-foreground">{section.badge}</p>
                </div>
              </div>

              <Card className="border-border/50 bg-card/50">
                <CardContent className="pt-5 space-y-5">
                  {section.content.map(item => (
                    <div key={item.heading} className="space-y-1.5">
                      <h3 className="font-semibold text-sm">{item.heading}</h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">{item.body}</p>
                    </div>
                  ))}
                  {section.id === "contact" && (
                    <div className="pt-2 flex flex-wrap gap-2">
                      <Button variant="outline" size="sm" className="gap-2" disabled>
                        <Mail className="h-3.5 w-3.5" />
                        Email Support
                        <ExternalLink className="h-3 w-3 opacity-60" />
                      </Button>
                    </div>
                  )}
                </CardContent>
              </Card>
            </section>
          ))}
        </div>

        <div className="flex items-center gap-3 p-4 rounded-xl bg-primary/5 border border-primary/20">
          <Lock className="h-5 w-5 text-primary shrink-0" />
          <div>
            <p className="text-sm font-medium">Your data is safe with Spark</p>
            <p className="text-xs text-muted-foreground">We use industry-standard encryption for all data in transit and at rest. We never sell your data.</p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
